#include "triton_bridge.h"
#include <fstream>
#include <sstream>
#include <iostream>
#include <stdexcept>
#include <cstdlib>
#include <chrono>
#include <cmath>
#include <regex>
#include <nlohmann/json.hpp>   // header-only JSON — add to deps

namespace rba {

using json = nlohmann::json;

TritonBridge::TritonBridge(const RBAConfig& cfg) : cfg_(cfg) {}

// ─── Design loading ────────────────────────────────────────────────────────

bool TritonBridge::load_design(const std::string& lef,
                                const std::string& def,
                                const std::string& guide) {
    lef_file_   = lef;
    def_file_   = def;
    guide_file_ = guide;

    // Extract design name from DEF header
    std::ifstream f(def);
    if (!f) {
        std::cerr << "[Bridge] Cannot open DEF: " << def << "\n";
        return false;
    }
    std::string line;
    std::regex design_re(R"(DESIGN\s+(\S+)\s*;)");
    std::regex nets_re(R"(NETS\s+(\d+)\s*;)");
    while (std::getline(f, line)) {
        std::smatch m;
        if (std::regex_search(line, m, design_re)) design_name_ = m[1];
        if (std::regex_search(line, m, nets_re))   total_nets_ = std::stoi(m[1]);
        if (!design_name_.empty() && total_nets_ > 0) break;
    }
    std::cout << "[Bridge] Loaded design: " << design_name_
              << " (" << total_nets_ << " nets)\n";
    return true;
}

// ─── Net order injection ───────────────────────────────────────────────────

void TritonBridge::inject_net_order(const std::vector<net_id>& order) {
    pending_net_order_ = order;
    std::cout << "[Bridge] Staged net order (" << order.size() << " nets)\n";
}

// ─── Cost weight injection ────────────────────────────────────────────────

void TritonBridge::inject_cost_weights(const CostWeights& w) {
    pending_cost_weights_ = w;
    std::cout << "[Bridge] Staged cost weights: wire=" << w.w_wire
              << " via=" << w.w_via << " cong=" << w.w_cong << "\n";
}

// ─── Forced rip-up injection ───────────────────────────────────────────────

void TritonBridge::inject_ripup_nets(const std::vector<net_id>& nets) {
    pending_ripup_nets_ = nets;
    std::cout << "[Bridge] Staged forced rip-up (" << nets.size() << " nets)\n";
}

// ─── net_id → name file resolution ─────────────────────────────────────────

void TritonBridge::write_net_name_file(const std::vector<net_id>& ids,
                                        const std::string& path) const {
    std::ofstream out(path);
    if (!out) throw std::runtime_error("Cannot write " + path);
    for (net_id id : ids) {
        auto it = net_names_.find(id);
        if (it != net_names_.end()) out << it->second << "\n";
    }
}

// ─── TritonRoute invocation ────────────────────────────────────────────────

bool TritonBridge::run_tritonroute(const TritonRunConfig& run_cfg) {
    std::string tcl = write_tcl_script(run_cfg);
    std::string tcl_path = cfg_.output_dir + "/run_route.tcl";
    {
        std::ofstream f(tcl_path);
        f << tcl;
    }

    // Build OpenROAD command
    std::ostringstream cmd;
    cmd << cfg_.openroad_bin
        << " -exit"
        << (run_cfg.verbose ? "" : " -no_init")
        << " " << tcl_path
        << " 2>&1 | tee " << cfg_.output_dir << "/openroad.log";

    std::cout << "[Bridge] Running: " << cmd.str() << "\n";

    auto t0 = std::chrono::steady_clock::now();
    int ret = std::system(cmd.str().c_str());
    auto t1 = std::chrono::steady_clock::now();
    ++invocation_count_;

    double elapsed = std::chrono::duration<double>(t1 - t0).count();
    std::cout << "[Bridge] TritonRoute finished in " << elapsed
              << "s (exit=" << ret << ", invocation #" << invocation_count_ << ")\n";

    return (ret == 0);
}

// ─── Tcl script generation ─────────────────────────────────────────────────
//
// Emits real Tcl calls to the RBA-specific commands added by
// third_party/openroad.patch (set_drt_cost_weights, set_drt_net_order,
// set_drt_ripup_nets — see docs/INTEGRATION.md). Each call is guarded by an
// `info commands` check so this script still runs correctly (falling back
// to TritonRoute's own defaults, with a logged warning) against a stock,
// unpatched OpenROAD build.

std::string TritonBridge::write_tcl_script(const TritonRunConfig& run_cfg) {
    std::ostringstream tcl;
    tcl << "# Auto-generated by RBA bridge\n";
    tcl << "read_lef " << run_cfg.lef_file << "\n";
    tcl << "read_def " << run_cfg.def_file << "\n";
    tcl << "\n";

    if (pending_cost_weights_) {
        const CostWeights& w = *pending_cost_weights_;
        // Map RBA's [0.1, 20.0] float weights onto TritonRoute's native
        // integer cost knobs, scaled so RBA's defaults reproduce
        // TritonRoute's own defaults (ROUTESHAPECOST=8, VIACOST=4,
        // MARKERCOST=32, GRIDCOST=2). w_cong/w_timing have no direct
        // TritonRoute cost-model analog yet and are not sent.
        auto to_cost = [](float rba_weight, double scale) {
            long v = std::lround(rba_weight * scale);
            return v < 1 ? 1 : v;
        };
        tcl << "if {[llength [info commands set_drt_cost_weights]] > 0} {\n";
        tcl << "  set_drt_cost_weights"
            << " -route_shape_cost " << to_cost(w.w_wire, 8.0)
            << " -via_cost "         << to_cost(w.w_via, 1.0)
            << " -marker_cost "      << to_cost(w.w_drc_hist, 6.4)
            << " -grid_cost "        << to_cost(w.w_layer_pref, 2.0)
            << "\n";
        tcl << "} else {\n";
        tcl << "  puts \"\\[RBA\\] WARNING: set_drt_cost_weights unavailable "
               "(unpatched OpenROAD build) — using TritonRoute defaults\"\n";
        tcl << "}\n\n";
        pending_cost_weights_.reset();
    }

    if (pending_net_order_) {
        std::string order_path = cfg_.output_dir + "/net_order.txt";
        write_net_name_file(*pending_net_order_, order_path);
        tcl << "if {[llength [info commands set_drt_net_order]] > 0} {\n";
        tcl << "  set_drt_net_order -file " << order_path << "\n";
        tcl << "} else {\n";
        tcl << "  puts \"\\[RBA\\] WARNING: set_drt_net_order unavailable "
               "(unpatched OpenROAD build) — net order ignored\"\n";
        tcl << "}\n\n";
        pending_net_order_.reset();
    }

    if (pending_ripup_nets_) {
        std::string ripup_path = cfg_.output_dir + "/ripup_nets.txt";
        write_net_name_file(*pending_ripup_nets_, ripup_path);
        tcl << "if {[llength [info commands set_drt_ripup_nets]] > 0} {\n";
        tcl << "  set_drt_ripup_nets -file " << ripup_path << "\n";
        tcl << "} else {\n";
        tcl << "  puts \"\\[RBA\\] WARNING: set_drt_ripup_nets unavailable "
               "(unpatched OpenROAD build) — forced rip-up ignored\"\n";
        tcl << "}\n\n";
        pending_ripup_nets_.reset();
    }

    // TritonRoute detailed routing command
    tcl << "detailed_route \\\n";
    tcl << "  -guide " << run_cfg.guide_file << " \\\n";
    tcl << "  -output_drc " << run_cfg.drc_report << " \\\n";
    tcl << "  -output_maze " << cfg_.output_dir << "/maze.log \\\n";
    tcl << "  -verbose " << run_cfg.verbose << " \\\n";
    tcl << "  -threads " << run_cfg.threads << "\n\n";

    tcl << "write_def " << run_cfg.output_def << "\n";

    // Write GCell congestion report
    tcl << "report_design_area\n";
    tcl << "report_wire_length\n";

    return tcl.str();
}

// ─── DRC marker parsing ────────────────────────────────────────────────────

std::vector<DRCMarker> TritonBridge::read_drc_markers(
        const std::string& drc_report) {
    // Try JSON format first (ISPD 2018+ TritonRoute output)
    if (drc_report.size() >= 5 &&
        drc_report.substr(drc_report.size()-5) == ".json") {
        return parse_drc_json(drc_report);
    }
    return parse_drc_rpt(drc_report);
}

std::vector<DRCMarker> TritonBridge::parse_drc_json(
        const std::string& path) const {
    std::vector<DRCMarker> markers;
    std::ifstream f(path);
    if (!f) return markers;

    json j;
    try { f >> j; } catch (...) { return markers; }

    for (auto& viol : j["violations"]) {
        DRCMarker m;
        auto& bbox = viol["bbox"];
        m.region = {bbox[0], bbox[1], bbox[2], bbox[3]};
        m.layer  = viol.value("layer_idx", 0);

        std::string type_str = viol.value("type", "OTHER");
        if      (type_str == "SHORT")    m.type = DRCType::SHORT;
        else if (type_str == "SPACING")  m.type = DRCType::SPACING;
        else if (type_str == "WIDTH")    m.type = DRCType::WIDTH;
        else if (type_str == "ENCLOSURE")m.type = DRCType::ENCLOSURE;
        else                             m.type = DRCType::OTHER;

        m.severity  = 1.0f;
        m.net1      = viol.value("net1_id", DRCMarker::INVALID);
        m.net2      = viol.value("net2_id", DRCMarker::INVALID);
        markers.push_back(m);
    }
    std::cout << "[Bridge] Parsed " << markers.size() << " DRC markers\n";
    return markers;
}

std::vector<DRCMarker> TritonBridge::parse_drc_rpt(
        const std::string& path) const {
    // Parse TritonRoute's text DRC report:
    //   violation type: Short
    //     srcs: net1 net2
    //     bbox = (xl yl) - (xh yh) on Layer M1
    std::vector<DRCMarker> markers;
    std::ifstream f(path);
    if (!f) return markers;

    std::string line;
    DRCMarker cur;
    bool in_viol = false;

    while (std::getline(f, line)) {
        if (line.find("violation type:") != std::string::npos) {
            if (in_viol) markers.push_back(cur);
            cur = DRCMarker{};
            in_viol = true;
            if (line.find("Short") != std::string::npos)   cur.type = DRCType::SHORT;
            else if (line.find("Spacing") != std::string::npos) cur.type = DRCType::SPACING;
            else cur.type = DRCType::OTHER;
            cur.severity = 1.0f;
        } else if (in_viol && line.find("bbox") != std::string::npos) {
            // Parse: bbox = (xl yl) - (xh yh) on Layer Mx
            std::regex bbox_re(R"(\((\d+)\s+(\d+)\)\s*-\s*\((\d+)\s+(\d+)\))");
            std::smatch bm;
            if (std::regex_search(line, bm, bbox_re)) {
                cur.region = {std::stoi(bm[1]), std::stoi(bm[2]),
                              std::stoi(bm[3]), std::stoi(bm[4])};
            }
            // Layer number heuristic: "Layer metal1" → 0, "metal2" → 1 ...
            std::regex layer_re(R"(Layer\s+\w*(\d+))");
            std::smatch lm;
            if (std::regex_search(line, lm, layer_re)) {
                cur.layer = static_cast<layer_t>(std::stoi(lm[1]) - 1);
            }
        }
    }
    if (in_viol) markers.push_back(cur);

    std::cout << "[Bridge] Parsed " << markers.size() << " DRC markers (RPT)\n";
    return markers;
}

// ─── Routing snapshot ──────────────────────────────────────────────────────

RoutingSnapshot TritonBridge::read_routing_snapshot(
        const std::string& output_def,
        double runtime_sec,
        const CostWeights& weights) {
    RoutingSnapshot snap;
    snap.runtime_sec   = runtime_sec;
    snap.weights_used  = weights;
    snap.total_drc     = 0;
    snap.total_via     = 0;
    snap.total_wirelength = 0.0;
    snap.unrouted_nets = 0;

    // Parse DEF for wire/via statistics
    std::ifstream f(output_def);
    if (!f) return snap;

    std::string line;
    std::regex via_re(R"(\bNEW\b.*\+\s*VIA\b)");
    std::regex wire_re(R"(ROUTED\s+\S+\s+\d+\s+\((\d+)\s+(\d+)\)\s+\((\d+)\s+(\d+)\))");
    std::regex unrouted_re(R"(UNROUTED)");

    while (std::getline(f, line)) {
        if (std::regex_search(line, via_re)) ++snap.total_via;
        std::smatch wm;
        if (std::regex_search(line, wm, wire_re)) {
            long dx = std::abs(std::stol(wm[3]) - std::stol(wm[1]));
            long dy = std::abs(std::stol(wm[4]) - std::stol(wm[2]));
            snap.total_wirelength += dx + dy;
        }
        if (std::regex_search(line, unrouted_re)) ++snap.unrouted_nets;
    }

    // Read DRC count from most recent DRC report
    std::string drc_rpt = cfg_.output_dir + "/drc.rpt";
    std::ifstream drc_f(drc_rpt);
    if (drc_f) {
        std::regex total_re(R"(Total\s+Violations\s*:\s*(\d+))");
        while (std::getline(drc_f, line)) {
            std::smatch dm;
            if (std::regex_search(line, dm, total_re)) {
                snap.total_drc = std::stoi(dm[1]);
                break;
            }
        }
    }

    std::cout << "[Bridge] Snapshot: DRC=" << snap.total_drc
              << " via=" << snap.total_via
              << " WL=" << snap.total_wirelength
              << " unrouted=" << snap.unrouted_nets
              << " t=" << snap.runtime_sec << "s\n";
    return snap;
}

// ─── Net loading (placeholder — extend with LEF/DEF parser) ───────────────

std::vector<Net> TritonBridge::load_nets(const std::string& def_file,
                                          const std::string& timing_rpt) {
    std::vector<Net> nets;
    // Minimal DEF NETS parser skeleton
    std::ifstream f(def_file);
    if (!f) return nets;

    std::string line;
    bool in_nets = false;
    Net cur_net;
    cur_net.id = 0;

    std::regex net_re(R"(^\s*-\s+(\S+)\s*)");
    std::regex pin_re(R"(\(\s*(\S+)\s+(\S+)\s*\))");
    std::regex end_re(R"(^\s*END\s+NETS)");

    while (std::getline(f, line)) {
        if (line.find("NETS") != std::string::npos && !in_nets) {
            in_nets = true; continue;
        }
        if (in_nets && std::regex_search(line, end_re)) break;
        if (!in_nets) continue;

        std::smatch m;
        if (std::regex_search(line, m, net_re)) {
            if (!cur_net.name.empty()) {
                net_names_[cur_net.id] = cur_net.name;
                nets.push_back(cur_net);
            }
            cur_net = Net{};
            cur_net.id = static_cast<net_id>(nets.size());
            cur_net.name = m[1];
            cur_net.is_clock = (cur_net.name.find("clk") != std::string::npos ||
                                cur_net.name.find("CLK") != std::string::npos);
            cur_net.is_power = (cur_net.name == "VDD" || cur_net.name == "VSS" ||
                                cur_net.name == "VCC" || cur_net.name == "GND");
        }

        // Count pin connections as a rough fanout estimate
        for (auto it = std::sregex_iterator(line.begin(), line.end(), pin_re);
             it != std::sregex_iterator(); ++it) {
            cur_net.pins.push_back(Pin{{0,0,0}, "M1", cur_net.id});
        }
    }
    if (!cur_net.name.empty()) {
        net_names_[cur_net.id] = cur_net.name;
        nets.push_back(cur_net);
    }

    // Apply timing priorities if report provided
    if (!timing_rpt.empty()) {
        std::ifstream tf(timing_rpt);
        // Simplified: assign priority by appearance order in timing report
        // Real implementation: parse OpenSTA -path_delay report
        std::unordered_map<std::string, int> rank;
        int r = 0;
        std::string tline;
        while (std::getline(tf, tline)) {
            for (auto& net : nets) {
                if (rank.count(net.name) == 0 &&
                    tline.find(net.name) != std::string::npos) {
                    rank[net.name] = r++;
                }
            }
        }
        for (auto& net : nets) {
            auto it = rank.find(net.name);
            net.priority = (it != rank.end()) ? it->second : (int)nets.size();
        }
    } else {
        // Default: sort by pin count descending
        int i = 0;
        for (auto& net : nets) net.priority = i++;
    }

    std::cout << "[Bridge] Loaded " << nets.size() << " nets\n";
    return nets;
}

// ─── Congestion estimation from guides ────────────────────────────────────

CongestionMap TritonBridge::estimate_congestion_from_guides(
        const std::string& guide_file) {
    CongestionMap cmap;
    // Simplified: count guide density per GCell region
    // Full implementation would parse the guide file's rectangular regions
    // and increment counters for each GCell they overlap
    std::cout << "[Bridge] Building congestion map from " << guide_file << "\n";

    // Placeholder — real impl reads guide regions and computes GCell densities
    cmap.gcell_nx = 10; cmap.gcell_ny = 10; cmap.n_layers = 6;
    cmap.cells.resize(cmap.gcell_nx * cmap.gcell_ny * cmap.n_layers);
    return cmap;
}

// ─── Route I/O stubs ──────────────────────────────────────────────────────

RoutingGraph TritonBridge::extract_routing_graph() {
    // Full implementation: walk the DEF routing tracks + via definitions
    // to build the edge/node graph for ACO.
    // This is O(tracks × layers) — typically 10M–100M nodes for real designs.
    RoutingGraph g;
    std::cout << "[Bridge] extract_routing_graph: stub — implement via DEF/LEF parser\n";
    return g;
}

std::vector<Route> TritonBridge::extract_routes(const std::string& def_file) {
    std::vector<Route> routes;
    parse_def_nets(def_file, routes);
    return routes;
}

bool TritonBridge::write_routes(const std::vector<Route>& routes,
                                 const std::string& input_def,
                                 const std::string& output_def) {
    // Rewrite DEF NETS section with updated via placements.
    // Full implementation: read entire DEF, replace NETS section.
    std::cout << "[Bridge] write_routes: writing " << routes.size()
              << " routes to " << output_def << "\n";
    // Copy input DEF → output DEF with modified nets
    std::ifstream in(input_def);
    std::ofstream out(output_def);
    if (!in || !out) return false;
    out << in.rdbuf();  // stub: copy as-is, real impl patches NETS section
    return true;
}

void TritonBridge::parse_def_nets(const std::string& def_path,
                                   std::vector<Route>& routes) const {
    // Skeleton: parse DEF NETS section routing geometry
    // Full implementation follows the DEF 5.8 grammar for ROUTED/NEW/VIA
    std::ifstream f(def_path);
    if (!f) return;
    // [implementation details omitted for brevity — see DEF parser spec]
    std::cout << "[Bridge] parse_def_nets: stub for " << def_path << "\n";
}

} // namespace rba
